# Plugins

require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

# Ignore files

AllCops:
  NewCops: enable
  Exclude:
    - 'db/**/*'
    - 'bin/**/*'
  TargetRubyVersion: 3.1
  TargetRailsVersion: 7.0

# Metrics Cops

Metrics/ClassLength:
  Description: 'Avoid classes longer than 100 lines of code.'
  Max: 100
  Enabled: true

Metrics/ModuleLength:
  Description: 'Avoid modules longer than 100 lines of code.'
  Max: 100
  Enabled: true

Metrics/ParameterLists:
  Description: 'Pass no more than four parameters into a method.'
  Max: 4
  Enabled: true

Metrics/MethodLength:
  Description: 'Avoid methods longer than 5 lines of code.'
  StyleGuide: '<https://github.com/bbatsov/ruby-style-guide#short-methods>'
  Max: 5
  Enabled: true

Metrics/BlockLength:
  CountComments: false
  Max: 5
  AllowedMethods:
    - context
    - describe
    - it
    - shared_examples
    - shared_examples_for
    - namespace
    - draw
    - configure
    - group
  Exclude:
    - 'app/admin/**/*'
    - 'app/controllers/api/**/*'
    - 'config/initializers/active_admin.rb'
    - 'config/initializers/devise.rb'

# Layout cops

Layout/LineLength:
 Max: 200

 # RSpec

RSpec/MultipleExpectations:
  Max: 10