version: "3"

services:
  nginx:
    image: linuxserver/swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Warsaw
      - URL=sharenite.link
      - SUBDOMAINS=wildcard
      - VALIDATION=dns
      - DNSPLUGIN=ovh
      - EMAIL=admin@sharenite.link
    volumes:
      - ./nginx:/config
      - ~/production:/production      
      - ~/staging:/staging
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped
    network_mode: host
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G