version: '3'
networks:
  development:
  test:
volumes:
  db_data:
  gem_cache:
  shared_data:
services:

  sharenite-redis:
    image: redis:7-alpine
    command: redis-server
    networks:
      - development
      - test
    volumes:
      - shared_data:/var/shared/redis
    ports:
      - 6379:6379

  sharenite-database:
    image: postgres:14-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
      - shared_data:/var/shared
    networks:
      - development
      - test
    environment:
      POSTGRES_USER: sharenite
      POSTGRES_PASSWORD: sharenite
    ports:
      - 5432:5432

  sharenite-webapp:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ../:/var/app
      - shared_data:/var/shared
      - gem_cache:/usr/local/bundle/gems
    networks:
      - development
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
    entrypoint: dev-entrypoint.sh
    command: ['rails', 'server', '-p', '3000', '-b', '0.0.0.0']
    environment:
      RAILS_ENV: development
    depends_on:
      - sharenite-database

  sharenite-js:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ../:/var/app
      - shared_data:/var/shared
      - gem_cache:/usr/local/bundle/gems
    networks:
      - development
    stdin_open: true
    tty: true
    entrypoint: dev-entrypoint.sh
    command: ['yarn', 'build', '--watch']
    environment:
      RAILS_ENV: development
    depends_on:
      - sharenite-database

  sharenite-css:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ../:/var/app
      - shared_data:/var/shared
      - gem_cache:/usr/local/bundle/gems
    networks:
      - development
    stdin_open: true
    tty: true
    entrypoint: dev-entrypoint.sh
    command: ['yarn', 'build:css', '--watch']
    environment:
      RAILS_ENV: development
    depends_on:
      - sharenite-database

  sharenite-sidekiq:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ../:/var/app
      - shared_data:/var/shared
      - gem_cache:/usr/local/bundle/gems
    networks:
      - development
    stdin_open: true
    tty: true
    entrypoint: dev-entrypoint.sh
    command: ['sidekiq']
    environment:
      RAILS_ENV: development
    depends_on:
      - sharenite-database
      - sharenite-redis

  sharenite-test:
    image: sharenite_sharenite_app
    volumes:
      - ../:/var/app
      - shared_data:/var/shared
      - gem_cache:/usr/local/bundle/gems
    networks:
      - test
    ports:
      - 3001:3000
    stdin_open: true
    tty: true
    entrypoint: test-entrypoint.sh
    command: ["rails", "-v"]
    environment:
      RAILS_ENV: test
    depends_on:
      - sharenite-database