---
default:
  push_api_key: "<%= Rails.application.credentials.appsignal %>"
  name: Sharenite
development:
  push_api_key: "<%= Rails.application.credentials.appsignal %>"
  name: Sharenite
  active: true
test:
  push_api_key: "<%= Rails.application.credentials.appsignal %>"
  name: Sharenite
  active: false
production:
  push_api_key: "<%= Rails.application.credentials.appsignal %>"
  name: Sharenite
  active: true
  revision: 8c52816
staging:
  push_api_key: "<%= Rails.application.credentials.appsignal %>"
  name: Sharenite
  active: true
